# 01 Intro - Homework - Ahmed Elsherif

#### Setup the environment

In [9]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

## Q1. Pandas version
- What version of Pandas did you install?
- **Answer:** `2.2.3`

In [10]:
pd.__version__

'2.2.3'

#### Getting the data

In [3]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-14 15:35:29--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.04s   

2026-09-14 15:35:29 (14.2 MB/s) - ‘car_fuel_efficiency_2026.csv’ saved [635180/635180]



In [5]:
data = pd.read_csv("car_fuel_efficiency_2026.csv")


## Q2. Records count
- How many records are in the dataset?
- **Answer:** `10000`

In [11]:
print(f"Records count: {data.shape[0]} - acquired from shape")
print(f"Records count: {len(data)} - acquired from length")

Records count: 10000 - acquired from shape
Records count: 10000 - acquired from length


## Q3. Fuel types
- How many fuel types are presented in the dataset?
- **Answer:** `3`

In [13]:
print(f"Fuel types count: {data['fuel_type'].nunique()}")
print(f"\nFuel Types Breakdown:\n{data['fuel_type'].value_counts()}")


Fuel types count: 3

Fuel Types Breakdown:
fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64


## Q4. Missing values
- How many columns in the dataset have missing values?
- **Answer:** `2`

In [15]:
print(f"Count of columns with missing values: {len(data.isnull().sum()[data.isnull().sum()>0].index)}")

print(f"\nMissing values per column:\n{data.isnull().sum()}")

Count of columns with missing values: 2

Missing values per column:
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64


## Q5. Max fuel efficiency
- What's the maximum fuel efficiency of cars from Asia?
- **Answer:** `41.2`

In [17]:
print(f"Max Fuel Efficiency from Asia: {data[data['origin']=='Asia']['fuel_efficiency_mpg'].max():.2f}")

Max Fuel Efficiency from Asia: 41.20


## Q6. Median value of horsepower
- Find the median value of the horsepower column in the dataset.
- **Answer:** `254`

In [18]:
print(f"Median Horse Power: {data['horsepower'].median()}")

Median Horse Power: 254.0


- Next, calculate the most frequent value of the same horsepower column.
- **Answer**: `252`

In [20]:
most_frequent_horse_power = data['horsepower'].mode().item()
print(f"Most frequent horse power: {most_frequent_horse_power}")

Most frequent horse power: 252.0


- Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

In [21]:
data['horsepower'] = data['horsepower'].fillna(most_frequent_horse_power)


- Now, calculate the median value of horsepower once again.

- Has it changed?
- **Answer:** `Yes, it decreased`

In [22]:
print(f"Median Horse Power: {data['horsepower'].median()}")

Median Horse Power: 252.0


## Q7. Sum of weights


1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.

In [23]:
all_cars_from_asia = data[data['origin']=='Asia']
weight_and_year = all_cars_from_asia[['vehicle_weight', 'model_year']]
first_7_values = weight_and_year.head(7)
X = first_7_values.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

9. What's the sum of all the elements of the result?
Note: You just implemented linear regression. We'll talk about it in the next lesson.

    * **Answer** `0.369`

In [24]:
XTX = np.dot(X.T, X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [25]:
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [26]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [28]:
w = np.dot(np.dot(XTX_inverse, X.T), y)
round(sum(w),3)

np.float64(0.369)